/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 42a93f57a19cc60906b8ca4de57be1c5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		OPENAI_API_KEY: string;
		GITHUB_REPO_URL: string;
		GITHUB_TOKEN: string;
		GEMINI_API_KEY: string;
		GOOGLE_GENERATIVE_AI_API_KEY: string;
		WRANGLER_LOG: string;
		CLOUDFLARE_API_TOKEN: string;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "GITHUB_REPO_URL" | "GITHUB_TOKEN" | "GEMINI_API_KEY" | "GOOGLE_GENERATIVE_AI_API_KEY" | "WRANGLER_LOG" | "CLOUDFLARE_API_TOKEN">> {}
}
